model_checkpoint: "%MODEL.CHECKPOINT%"
ini_data_path: "%DIRS.INI_DATA_PATH%/%MODEL.NAME%/%MODEL.CHECKPOINT_NAME%/%CHUNK_START_DATE%-%CHUNK_END_DATE%"
start_time: '%CHUNK_START_YEAR%-%CHUNK_START_MONTH%-%CHUNK_START_DAY%'
end_time: '%CHUNK_END_YEAR%-%CHUNK_END_MONTH%-%CHUNK_END_DAY%'
data_inner_steps: 24 # process every 24th hour
inner_steps: 24 # save model outputs once every 24 hours
rng_key: "%MEMBER%"
output_path: "%HPCROOTDIR%/outputs/%MODEL.NAME%/%SDATE%/"
plots_path: "%HPCROOTDIR%/plots/%MODEL.NAME%/%SDATE%/"
members: "%EXPERIMENT.MEMBERS%"
