model_checkpoint: "%MODEL.CHECKPOINT%"
era5_path: "%DIRS.ERA5_PATH%/%MODEL.NAME%/%MODEL.CHECKPOINT%/%CHUNK_START_DATE%-%CHUNK_END_DATE%"
start_time: '2020-02-14'
end_time: '2020-02-18'
data_inner_steps: 24 # process every 24th hour
inner_steps: 24 # save model outputs once every 24 hours
rng_key: "%MEMBER%"
output_path: "%HPCROOTDIR%/outputs/%MODEL.NAME%/%SDATE%/%MEMBER%/"
